name: lepw-docker-push-to-docker-hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push PHP7.4
        uses: docker/build-push-action@v2
        with:
          context: ./7.4
          push: true
          tags: |
            solucionesgbh/lepw:main
            solucionesgbh/lepw:7.4
      - name: Build and push PHP7.3
        uses: docker/build-push-action@v2
        with:
          context: ./7.3
          push: true
          tags: solucionesgbh/lepw:7.3
      - name: Build and push PHP7.2
        uses: docker/build-push-action@v2
        with:
          context: ./7.2
          push: true
          tags: solucionesgbh/lepw:7.2
      - name: Build and push PHP7.1
        uses: docker/build-push-action@v2
        with:
          context: ./7.1
          push: true
          tags: solucionesgbh/lepw:7.1
